version: "3.9"
services:
  app:
    image: tdmvp_front
    container_name: tdmvp_front
    tty: true
    restart: always
    stdin_open: true
    ports:
      - "5779:3000"
    build:
      context: .
      dockerfile: Dockerfile
